### ISSUE TITLE
README refers to non-existing methods

### ISSUE THREAD

**Issue by sbartholomees** [mailslurp/mailslurp-client-java#2]
https://github.com/mailslurp/mailslurp-client-java/blob/master/README.md refers to for example CommonActionsControllerApi#waitForEmailCount. This method doesn't exist in https://github.com/mailslurp/mailslurp-client-java/blob/master/src/main/java/com/mailslurp/api/api/CommonActionsControllerApi.java.

**Comment by jackmahoney** [comment]
@sbartholomees thank you for pointing this out. We use swagger codegen to generate our libraries with each release. We didn't have any automated test in place tho and some recent API changes broke the Java clients and some of there docs. We have fixed the release on master now and will fix the docs next
