### ISSUE TITLE
Is this service still active?

### ISSUE THREAD

**Issue by SHxKM** [mailslurp/mailslurp-client-java#4]
I've contacted your support 3 times over the past two months and no response. It seems that you are updating your repos though, so just no support? I'm a paying customer on behalf of a company I work for.

**Comment by jackmahoney** [comment]
Hi, sorry for the delay. **YES we are still active**. We have had problems with the current global situation so we appreciate your patience.

**Comment by SHxKM** [comment]
@jackmahoney thanks for responding and for the good news. I have opened a ticket through Zendesk; I can’t share here unfortunately as some code belongs to my company.

**Comment by jackmahoney** [comment]
Thanks for understanding. I will look right now
