### ISSUE TITLE
Update your documentation and this repository as JCenter is is deprecated

### ISSUE THREAD

**Issue by gruckionvit** [mailslurp/mailslurp-client-java#5]
The documentation has [Install with Maven](https://www.mailslurp.com/docs/java/#install-using-maven), but JCenter is shutting down in May.

Please check your package published [here](https://bintray.com/mailslurp/mailslurp-client/mailslurp-client-java). As you can see (image below)

> Attention: All Bintray services will be deprecated and your accounts will be disabled on May 1st 2021. [Learn More](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter).

![Screenshot 2021-03-24 at 14 52 57](https://user-images.githubusercontent.com/67283459/112331213-9fea5780-8cb0-11eb-8a95-98e1c7f4bd7a.png)

Where are we supposed to go to find the repository?

**Comment by gruckionvit** [comment]
For anyone else, see this issue.

https://github.com/mailslurp/mailslurp-client-java/issues/1#issuecomment-620173832

> Hi @ochubey @sbartholomees I have released a compiling build on JitPack now
>
> https://jitpack.io/#mailslurp/mailslurp-client-java/7.0.11-RELEASE

![Screenshot 2021-03-24 at 15 02 39](https://user-images.githubusercontent.com/67283459/112332842-fc9a4200-8cb1-11eb-94f5-51453aefae3b.png)

**Comment by gruckionvit** [comment]
@jackmahoney can you provide some clarity (where do you recommend I source the dependency)? Would be great if you can keep the docs upto date too. (I know it's rough when you are supporting so many languages. Thank you for the very useful product.

**Comment by jackmahoney** [comment]
Hi thanks for raising this. I appreciate. We do have a plan to migrate before the sunset but it has been taking a while. I have opened a ticket at maven central and it has been approved so the next step is to configure our build process to publish to maven central. I imagine this will be done in 1-2 weeks. Sorry about the tight timelime. I will post on this ticket and twitter new documentation once it is done. Thanks again

**Comment by gruckionvit** [comment]
Cheers

**Comment by jackmahoney** [comment]
Maven jira ticket here (old one was closed)

https://issues.sonatype.org/browse/OSSRH-66333

**Comment by jackmahoney** [comment]
@gruckionvit release complete https://search.maven.org/artifact/com.mailslurp/mailslurp-client-java/
